trigger:
  - multipleEnvs

pool:
  vmImage: ubuntu-latest
steps:

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'ananda18'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
