# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- buildRelease

jobs:
  - job: Build
    pool: 
      vmImage: ubuntu-latest
    

    steps:
     - task: DockerCompose@0
       inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run services'
        
     - task: Maven@3
       inputs:
         mavenPomFile: 'pom.xml'
         mavenOptions: '-Xmx3072m'
         javaHomeOption: 'JDKVersion'
         jdkVersionOption: '1.8'
         jdkArchitectureOption: 'x64'
         goals: 'install -DskipTests -Dgatling.skip'
      
     - task: CopyFiles@2
       inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: 'API_LAB'
         TargetFolder: '$(System.DefaultWorkingDirectory)'

     

     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(System.DefaultWorkingDirectory)'
         ArtifactName: 'API and Load Automation'
         publishLocation: 'Container'

     
      
  
  
