trigger:
  - multipleEnvs
stages: 
  - stage: PerformanceTest 
    jobs:
      - job: DeployContainer 
        pool:
          vmImage: ubuntu-latest 

        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub'
              command: 'login'
          
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'localhost:8500/smartqe/qe-vehicle-v1'
              command: 'push'
              tags: 'latest'
              
      - job: RunTest
        dependsOn: DeployContainer
        condition: succeeded()
        pool:
          vmImage: ubuntu-latest 
          
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'clean test -P gatling'